INSERT INTO "attributes" ("id", "vendor_id", "name", "number", "type", "description")
VALUES 
(267, NULL,'Fall-Through','500','integer','Freeradius Internal'),
(268, NULL,'Relax-Filter','501','integer','Freeradius Internal'),
(269, NULL,'Exec-Program','502','string','Freeradius Internal'),
(270, NULL,'Exec-Program-Wait','503','string','Freeradius Internal'),
(271, NULL,'Auth-Type','1000','integer','Freeradius Internal'),
(272, NULL,'Menu','1001','string','Freeradius Internal'),
(273, NULL,'Termination-Menu','1002','string','Freeradius Internal'),
(274, NULL,'Prefix','1003','string','Freeradius Internal'),
(275, NULL,'Suffix','1004','string','Freeradius Internal'),
(276, NULL,'Group','1005','string','Freeradius Internal'),
(277, NULL,'Crypt-Password','1006','string','Freeradius Internal'),
(278, NULL,'Add-Prefix','1008','string','Freeradius Internal'),
(279, NULL,'Add-Suffix','1009','string','Freeradius Internal'),
(280, NULL,'Expiration','1010','date','Freeradius Internal'),
(281, NULL,'Autz-Type','1011','integer','Freeradius Internal'),
(282, NULL,'Acct-Type','1012','integer','Freeradius Internal'),
(283, NULL,'Session-Type','1013','integer','Freeradius Internal'),
(284, NULL,'Post-Auth-Type','1014','integer','Freeradius Internal'),
(285, NULL,'Pre-Proxy-Type','1015','integer','Freeradius Internal'),
(286, NULL,'Post-Proxy-Type','1016','integer','Freeradius Internal'),
(287, NULL,'Pre-Acct-Type','1017','integer','Freeradius Internal'),
(288, NULL,'EAP-Type','1018','integer','Freeradius Internal'),
(289, NULL,'EAP-TLS-Require-Client-Cert','1019','integer','Freeradius Internal'),
(290, NULL,'EAP-Id','1020','integer','Freeradius Internal'),
(291, NULL,'EAP-Code','1021','integer','Freeradius Internal'),
(292, NULL,'EAP-MD5-Password','1022','string','Freeradius Internal'),
(293, NULL,'PEAP-Version','1023','integer','Freeradius Internal'),
(294, NULL,'Client-Shortname','1024','string','Freeradius Internal'),
(295, NULL,'Load-Balance-Key','1025','string','Freeradius Internal'),
(296, NULL,'Raw-Raw-Attribute','1026','octets','Freeradius Internal'),
(297, NULL,'TNC-VLAN-Access','1027','string','Freeradius Internal'),
(298, NULL,'TNC-VLAN-Isolate','1028','string','Freeradius Internal'),
(299, NULL,'User-Category','1029','string','Freeradius Internal'),
(300, NULL,'Group-Name','1030','string','Freeradius Internal'),
(301, NULL,'Huntgroup-Name','1031','string','Freeradius Internal'),
(302, NULL,'Simultaneous-Use','1034','integer','Freeradius Internal'),
(303, NULL,'Strip-User-Name','1035','integer','Freeradius Internal'),
(304, NULL,'Hint','1040','string','Freeradius Internal'),
(305, NULL,'Pam-Auth','1041','string','Freeradius Internal'),
(306, NULL,'Login-Time','1042','string','Freeradius Internal'),
(307, NULL,'Stripped-User-Name','1043','string','Freeradius Internal'),
(308, NULL,'Current-Time','1044','string','Freeradius Internal'),
(309, NULL,'Realm','1045','string','Freeradius Internal'),
(310, NULL,'No-Such-Attribute','1046','string','Freeradius Internal'),
(311, NULL,'Packet-Type','1047','integer','Freeradius Internal'),
(312, NULL,'Proxy-To-Realm','1048','string','Freeradius Internal'),
(313, NULL,'Replicate-To-Realm','1049','string','Freeradius Internal'),
(314, NULL,'Acct-Session-Start-Time','1050','date','Freeradius Internal'),
(315, NULL,'Acct-Unique-Session-Id','1051','string','Freeradius Internal'),
(316, NULL,'Client-IP-Address','1052','ipaddr','Freeradius Internal'),
(317, NULL,'LDAP-UserDN','1053','string','Freeradius Internal'),
(318, NULL,'NS-MTA-MD5-Password','1054','string','Freeradius Internal'),
(319, NULL,'SQL-User-Name','1055','string','Freeradius Internal'),
(320, NULL,'LM-Password','1057','octets','Freeradius Internal'),
(321, NULL,'NT-Password','1058','octets','Freeradius Internal'),
(322, NULL,'SMB-Account-CTRL','1059','integer','Freeradius Internal'),
(323, NULL,'SMB-Account-CTRL-TEXT','1061','string','Freeradius Internal'),
(324, NULL,'User-Profile','1062','string','Freeradius Internal'),
(325, NULL,'Digest-Realm','1063','string','Freeradius Internal'),
(326, NULL,'Digest-Nonce','1064','string','Freeradius Internal'),
(327, NULL,'Digest-Method','1065','string','Freeradius Internal'),
(328, NULL,'Digest-URI','1066','string','Freeradius Internal'),
(329, NULL,'Digest-QOP','1067','string','Freeradius Internal'),
(330, NULL,'Digest-Algorithm','1068','string','Freeradius Internal'),
(331, NULL,'Digest-Body-Digest','1069','string','Freeradius Internal'),
(332, NULL,'Digest-CNonce','1070','string','Freeradius Internal'),
(333, NULL,'Digest-Nonce-Count','1071','string','Freeradius Internal'),
(334, NULL,'Digest-User-Name','1072','string','Freeradius Internal'),
(335, NULL,'Pool-Name','1073','string','Freeradius Internal'),
(336, NULL,'Module-Success-Message','1075','string','Freeradius Internal'),
(337, NULL,'Module-Failure-Message','1076','string','Freeradius Internal'),
(338, NULL,'Rewrite-Rule','1078','string','Freeradius Internal'),
(339, NULL,'Response-Packet-Type','1080','integer','Freeradius Internal'),
(340, NULL,'Digest-HA1','1081','string','Freeradius Internal'),
(341, NULL,'MS-CHAP-Use-NTLM-Auth','1082','integer','Freeradius Internal'),
(342, NULL,'NTLM-User-Name','1083','string','Freeradius Internal'),
(343, NULL,'MS-CHAP-User-Name','1083','string','Freeradius Internal'),
(344, NULL,'Packet-Src-IP-Address','1084','ipaddr','Freeradius Internal'),
(345, NULL,'Packet-Dst-IP-Address','1085','ipaddr','Freeradius Internal'),
(346, NULL,'Packet-Src-Port','1086','integer','Freeradius Internal'),
(347, NULL,'Packet-Dst-Port','1087','integer','Freeradius Internal'),
(348, NULL,'Packet-Authentication-Vector','1088','octets','Freeradius Internal'),
(349, NULL,'Time-Of-Day','1089','string','Freeradius Internal'),
(350, NULL,'Request-Processing-Stage','1090','string','Freeradius Internal'),
(351, NULL,'SHA2-Password','1092','octets','Freeradius Internal'),
(352, NULL,'SHA-Password','1093','octets','Freeradius Internal'),
(353, NULL,'SSHA-Password','1094','octets','Freeradius Internal'),
(354, NULL,'SHA1-Password','1093','octets','Freeradius Internal'),
(355, NULL,'SSHA1-Password','1094','octets','Freeradius Internal'),
(356, NULL,'MD5-Password','1095','octets','Freeradius Internal'),
(357, NULL,'SMD5-Password','1096','octets','Freeradius Internal'),
(358, NULL,'Packet-Src-IPv6-Address','1097','ipv6addr','Freeradius Internal'),
(359, NULL,'Packet-Dst-IPv6-Address','1098','ipv6addr','Freeradius Internal'),
(360, NULL,'Virtual-Server','1099','string','Freeradius Internal'),
(361, NULL,'Cleartext-Password','1100','string','Freeradius Internal'),
(362, NULL,'Password-With-Header','1101','string','Freeradius Internal'),
(363, NULL,'Inner-Tunnel-User-Name','1102','string','Freeradius Internal'),
(364, NULL,'EAP-IKEv2-IDType','1103','integer','Freeradius Internal'),
(365, NULL,'EAP-IKEv2-ID','1104','string','Freeradius Internal'),
(366, NULL,'EAP-IKEv2-Secret','1105','string','Freeradius Internal'),
(367, NULL,'EAP-IKEv2-AuthType','1106','integer','Freeradius Internal'),
(368, NULL,'Send-Disconnect-Request','1107','integer','Freeradius Internal'),
(369, NULL,'Send-CoA-Request','1107','integer','Freeradius Internal'),
(370, NULL,'Module-Return-Code','1108','integer','Freeradius Internal'),
(371, NULL,'Packet-Original-Timestamp','1109','date','Freeradius Internal'),
(372, NULL,'SQL-Table-Name','1110','string','Freeradius Internal'),
(373, NULL,'Home-Server-Pool','1111','string','Freeradius Internal'),
(374, NULL,'Attribute-Map','1112','string','Freeradius Internal'),
(375, NULL,'COA-Packet-Type','1113','string','Freeradius Internal'),
(376, NULL,'COA-Packet-DST-IP-Address','1114','ipaddr','Freeradius Internal'),
(377, NULL,'COA-Packet-DST-Port','1115','integer','Freeradius Internal'),
(378, NULL,'COA-Acct-Session-Id','1116','string','Freeradius Internal'),
(379, NULL,'FreeRADIUS-Client-IP-Address','1120','ipaddr','Freeradius Internal'),
(380, NULL,'FreeRADIUS-Client-IPv6-Address','1121','ipv6addr','Freeradius Internal'),
(381, NULL,'FreeRADIUS-Client-Require-MA','1122','integer','Freeradius Internal'),
(382, NULL,'FreeRADIUS-Client-Secret','1123','string','Freeradius Internal'),
(383, NULL,'FreeRADIUS-Client-Shortname','1124','string','Freeradius Internal'),
(384, NULL,'FreeRADIUS-Client-NAS-Type','1125','string','Freeradius Internal'),
(385, NULL,'FreeRADIUS-Client-Virtual-Server','1126','string','Freeradius Internal'),
(386, NULL,'Allow-Session-Resumption','1127','integer','Freeradius Internal'),
(387, NULL,'EAP-Session-Resumed','1128','integer','Freeradius Internal'),
(388, NULL,'EAP-MSK','1129','octets','Freeradius Internal'),
(389, NULL,'EAP-EMSK','1130','octets','Freeradius Internal'),
(390, NULL,'Recv-CoA-Type','1131','integer','Freeradius Internal'),
(391, NULL,'Send-CoA-Type','1132','integer','Freeradius Internal'),
(392, NULL,'MS-CHAP-Password','1133','string','Freeradius Internal'),
(393, NULL,'Packet-Transmit-Counter','1134','integer','Freeradius Internal'),
(394, NULL,'Cached-Session-Policy','1135','string','Freeradius Internal'),
(395, NULL,'MS-CHAP-New-Cleartext-Password','1136','string','Freeradius Internal'),
(396, NULL,'MS-CHAP-New-NT-Password','1137','octets','Freeradius Internal'),
(397, NULL,'Stripped-User-Domain','1138','string','Freeradius Internal'),
(398, NULL,'Called-Station-SSID','1139','string','Freeradius Internal'),
(399, NULL,'OTP-Challenge','1145','string','Freeradius Internal'),
(400, NULL,'EAP-Session-Id','1146','octets','Freeradius Internal'),
(401, NULL,'Chbind-Response-Code','1147','integer','Freeradius Internal'),
(402, NULL,'Acct-Input-Octets64','1148','integer64','Freeradius Internal'),
(403, NULL,'Acct-Output-Octets64','1149','integer64','Freeradius Internal'),
(404, NULL,'FreeRADIUS-Client-IP-Prefix','1150','ipv4prefix','Freeradius Internal'),
(405, NULL,'FreeRADIUS-Client-IPv6-Prefix','1151','ipv6prefix','Freeradius Internal'),
(406, NULL,'FreeRADIUS-Response-Delay','1152','integer','Freeradius Internal'),
(407, NULL,'FreeRADIUS-Client-Src-IP-Address','1153','ipaddr','Freeradius Internal'),
(408, NULL,'FreeRADIUS-Client-Src-IPv6-Address','1154','ipv6addr','Freeradius Internal'),
(409, NULL,'FreeRADIUS-Response-Delay-USec','1155','integer','Freeradius Internal'),
(410, NULL,'REST-HTTP-Header','1160','string','Freeradius Internal'),
(411, NULL,'REST-HTTP-Body','1161','string','Freeradius Internal'),
(412, NULL,'Cache-Expires','1170','date','Freeradius Internal'),
(413, NULL,'Cache-Created','1171','date','Freeradius Internal'),
(414, NULL,'Cache-TTL','1172','signed','Freeradius Internal'),
(415, NULL,'Cache-Status-Only','1173','integer','Freeradius Internal'),
(416, NULL,'Cache-Merge','1174','integer','Freeradius Internal'),
(417, NULL,'Cache-Entry-Hits','1175','integer','Freeradius Internal'),
(418, NULL,'Cache-Read-Only','1176','integer','Freeradius Internal'),
(419, NULL,'SSHA2-224-Password','1177','octets','Freeradius Internal'),
(420, NULL,'SSHA2-256-Password','1178','octets','Freeradius Internal'),
(421, NULL,'SSHA2-384-Password','1179','octets','Freeradius Internal'),
(422, NULL,'SSHA2-512-Password','1180','octets','Freeradius Internal'),
(423, NULL,'MS-CHAP-Peer-Challenge','1192','octets','Freeradius Internal'),
(424, NULL,'EAP-Sim-Subtype','1200','integer','Freeradius Internal'),
(425, NULL,'EAP-Sim-Rand1','1201','octets','Freeradius Internal'),
(426, NULL,'EAP-Sim-Rand2','1202','octets','Freeradius Internal'),
(427, NULL,'EAP-Sim-Rand3','1203','octets','Freeradius Internal'),
(428, NULL,'EAP-Sim-SRES1','1204','octets','Freeradius Internal'),
(429, NULL,'EAP-Sim-SRES2','1205','octets','Freeradius Internal'),
(430, NULL,'EAP-Sim-SRES3','1206','octets','Freeradius Internal'),
(431, NULL,'EAP-Sim-State','1207','integer','Freeradius Internal'),
(432, NULL,'EAP-Sim-IMSI','1208','string','Freeradius Internal'),
(433, NULL,'EAP-Sim-HMAC','1209','string','Freeradius Internal'),
(434, NULL,'EAP-Sim-KEY','1210','octets','Freeradius Internal'),
(435, NULL,'EAP-Sim-EXTRA','1211','octets','Freeradius Internal'),
(436, NULL,'EAP-Sim-KC1','1212','octets','Freeradius Internal'),
(437, NULL,'EAP-Sim-KC2','1213','octets','Freeradius Internal'),
(438, NULL,'EAP-Sim-KC3','1214','octets','Freeradius Internal'),
(439, NULL,'EAP-Sim-Ki','1215','octets','Freeradius Internal'),
(440, NULL,'EAP-Sim-Algo-Version','1216','integer','Freeradius Internal'),
(441, NULL,'Outer-Realm-Name','1218','string','Freeradius Internal'),
(442, NULL,'Inner-Realm-Name','1219','string','Freeradius Internal'),
(443, NULL,'EAP-Type-Base','1280','octets','Freeradius Internal'),
(444, NULL,'EAP-Type-VALUE','1280','octets','Freeradius Internal'),
(445, NULL,'EAP-Type-None','1280','octets','Freeradius Internal'),
(446, NULL,'EAP-Type-Identity','1281','octets','Freeradius Internal'),
(447, NULL,'EAP-Type-Notification','1282','octets','Freeradius Internal'),
(448, NULL,'EAP-Type-NAK','1283','octets','Freeradius Internal'),
(449, NULL,'EAP-Type-MD5-Challenge','1284','octets','Freeradius Internal'),
(450, NULL,'EAP-Type-One-Time-Password','1285','octets','Freeradius Internal'),
(451, NULL,'EAP-Type-Generic-Token-Card','1286','octets','Freeradius Internal'),
(452, NULL,'EAP-Type-RSA-Public-Key','1289','octets','Freeradius Internal'),
(453, NULL,'EAP-Type-DSS-Unilateral','1290','octets','Freeradius Internal'),
(454, NULL,'EAP-Type-KEA','1291','octets','Freeradius Internal'),
(455, NULL,'EAP-Type-KEA-Validate','1292','octets','Freeradius Internal'),
(456, NULL,'EAP-Type-EAP-TLS','1293','octets','Freeradius Internal'),
(457, NULL,'EAP-Type-Defender-Token','1294','octets','Freeradius Internal'),
(458, NULL,'EAP-Type-RSA-SecurID-EAP','1295','octets','Freeradius Internal'),
(459, NULL,'EAP-Type-Arcot-Systems-EAP','1296','octets','Freeradius Internal'),
(460, NULL,'EAP-Type-Cisco-LEAP','1297','octets','Freeradius Internal'),
(461, NULL,'EAP-Type-Nokia-IP-Smart-Card','1298','octets','Freeradius Internal'),
(462, NULL,'EAP-Type-SIM','1298','octets','Freeradius Internal'),
(463, NULL,'EAP-Type-SRP-SHA1','1299','octets','Freeradius Internal'),
(464, NULL,'EAP-Type-EAP-TTLS','1301','octets','Freeradius Internal'),
(465, NULL,'EAP-Type-Remote-Access-Service','1302','octets','Freeradius Internal'),
(466, NULL,'EAP-Type-AKA','1303','octets','Freeradius Internal'),
(467, NULL,'EAP-Type-EAP-3Com-Wireless','1304','octets','Freeradius Internal'),
(468, NULL,'EAP-Type-PEAP','1305','octets','Freeradius Internal'),
(469, NULL,'EAP-Type-MS-EAP-Authentication','1306','octets','Freeradius Internal'),
(470, NULL,'EAP-Type-MAKE','1307','octets','Freeradius Internal'),
(471, NULL,'EAP-Type-CRYPTOCard','1308','octets','Freeradius Internal'),
(472, NULL,'EAP-Type-EAP-MSCHAP-V2','1309','octets','Freeradius Internal'),
(473, NULL,'EAP-Type-DynamID','1310','octets','Freeradius Internal'),
(474, NULL,'EAP-Type-Rob-EAP','1311','octets','Freeradius Internal'),
(475, NULL,'EAP-Type-SecurID-EAP','1312','octets','Freeradius Internal'),
(476, NULL,'EAP-Type-MS-Authentication-TLV','1313','octets','Freeradius Internal'),
(477, NULL,'EAP-Type-SentriNET','1314','octets','Freeradius Internal'),
(478, NULL,'EAP-Type-EAP-Actiontec-Wireless','1315','octets','Freeradius Internal'),
(479, NULL,'EAP-Type-Cogent-Biomentric-EAP','1316','octets','Freeradius Internal'),
(480, NULL,'EAP-Type-AirFortress-EAP','1317','octets','Freeradius Internal'),
(481, NULL,'EAP-Type-EAP-HTTP-Digest','1318','octets','Freeradius Internal'),
(482, NULL,'EAP-Type-SecuriSuite-EAP','1319','octets','Freeradius Internal'),
(483, NULL,'EAP-Type-DeviceConnect-EAP','1320','octets','Freeradius Internal'),
(484, NULL,'EAP-Type-EAP-SPEKE','1321','octets','Freeradius Internal'),
(485, NULL,'EAP-Type-EAP-MOBAC','1322','octets','Freeradius Internal'),
(486, NULL,'EAP-Type-EAP-FAST','1323','octets','Freeradius Internal'),
(487, NULL,'EAP-Type-Zonelabs','1324','octets','Freeradius Internal'),
(488, NULL,'EAP-Type-EAP-Link','1325','octets','Freeradius Internal'),
(489, NULL,'EAP-Type-EAP-PAX','1326','octets','Freeradius Internal'),
(490, NULL,'EAP-Type-EAP-PSK','1327','octets','Freeradius Internal'),
(491, NULL,'EAP-Type-EAP-SAKE','1328','octets','Freeradius Internal'),
(492, NULL,'EAP-Type-EAP-IKEv2','1329','octets','Freeradius Internal'),
(493, NULL,'EAP-Type-EAP-AKA2','1330','octets','Freeradius Internal'),
(494, NULL,'EAP-Type-EAP-GPSK','1331','octets','Freeradius Internal'),
(495, NULL,'EAP-Type-EAP-PWD','1332','octets','Freeradius Internal'),
(496, NULL,'EAP-Type-EAP-EVEv1','1333','octets','Freeradius Internal'),
(497, NULL,'EAP-Type-Microsoft-MS-CHAPv2','1306','octets','Freeradius Internal'),
(498, NULL,'EAP-Type-Cisco-MS-CHAPv2','1309','octets','Freeradius Internal'),
(499, NULL,'EAP-Type-MS-CHAP-V2','1306','octets','Freeradius Internal'),
(500, NULL,'EAP_Sim-Base','1536','octets','Freeradius Internal'),
(501, NULL,'EAP-Sim-RAND','1537','octets','Freeradius Internal'),
(502, NULL,'EAP-Sim-PADDING','1542','octets','Freeradius Internal'),
(503, NULL,'EAP-Sim-NONCE_MT','1543','octets','Freeradius Internal'),
(504, NULL,'EAP-Sim-PERMANENT_ID_REQ','1546','octets','Freeradius Internal'),
(505, NULL,'EAP-Sim-MAC','1547','octets','Freeradius Internal'),
(506, NULL,'EAP-Sim-NOTIFICATION','1548','octets','Freeradius Internal'),
(507, NULL,'EAP-Sim-ANY_ID_REQ','1549','octets','Freeradius Internal'),
(508, NULL,'EAP-Sim-IDENTITY','1550','octets','Freeradius Internal'),
(509, NULL,'EAP-Sim-VERSION_LIST','1551','octets','Freeradius Internal'),
(510, NULL,'EAP-Sim-SELECTED_VERSION','1552','octets','Freeradius Internal'),
(511, NULL,'EAP-Sim-FULLAUTH_ID_REQ','1553','octets','Freeradius Internal'),
(512, NULL,'EAP-Sim-COUNTER','1555','octets','Freeradius Internal'),
(513, NULL,'EAP-Sim-COUNTER_TOO_SMALL','1556','octets','Freeradius Internal'),
(514, NULL,'EAP-Sim-NONCE_S','1557','octets','Freeradius Internal'),
(515, NULL,'EAP-Sim-IV','1665','octets','Freeradius Internal'),
(516, NULL,'EAP-Sim-ENCR_DATA','1666','octets','Freeradius Internal'),
(517, NULL,'EAP-Sim-NEXT_PSEUDONUM','1668','octets','Freeradius Internal'),
(518, NULL,'EAP-Sim-NEXT_REAUTH_ID','1669','octets','Freeradius Internal'),
(519, NULL,'EAP-Sim-CHECKCODE','1670','octets','Freeradius Internal'),
(520, NULL,'Tmp-String-0','1800','string','Freeradius Internal'),
(521, NULL,'Tmp-String-1','1801','string','Freeradius Internal'),
(522, NULL,'Tmp-String-2','1802','string','Freeradius Internal'),
(523, NULL,'Tmp-String-3','1803','string','Freeradius Internal'),
(524, NULL,'Tmp-String-4','1804','string','Freeradius Internal'),
(525, NULL,'Tmp-String-5','1805','string','Freeradius Internal'),
(526, NULL,'Tmp-String-6','1806','string','Freeradius Internal'),
(527, NULL,'Tmp-String-7','1807','string','Freeradius Internal'),
(528, NULL,'Tmp-String-8','1808','string','Freeradius Internal'),
(529, NULL,'Tmp-String-9','1809','string','Freeradius Internal'),
(530, NULL,'Tmp-Integer-0','1810','integer','Freeradius Internal'),
(531, NULL,'Tmp-Integer-1','1811','integer','Freeradius Internal'),
(532, NULL,'Tmp-Integer-2','1812','integer','Freeradius Internal'),
(533, NULL,'Tmp-Integer-3','1813','integer','Freeradius Internal'),
(534, NULL,'Tmp-Integer-4','1814','integer','Freeradius Internal'),
(535, NULL,'Tmp-Integer-5','1815','integer','Freeradius Internal'),
(536, NULL,'Tmp-Integer-6','1816','integer','Freeradius Internal'),
(537, NULL,'Tmp-Integer-7','1817','integer','Freeradius Internal'),
(538, NULL,'Tmp-Integer-8','1818','integer','Freeradius Internal'),
(539, NULL,'Tmp-Integer-9','1819','integer','Freeradius Internal'),
(540, NULL,'Tmp-IP-Address-0','1820','ipaddr','Freeradius Internal'),
(541, NULL,'Tmp-IP-Address-1','1821','ipaddr','Freeradius Internal'),
(542, NULL,'Tmp-IP-Address-2','1822','ipaddr','Freeradius Internal'),
(543, NULL,'Tmp-IP-Address-3','1823','ipaddr','Freeradius Internal'),
(544, NULL,'Tmp-IP-Address-4','1824','ipaddr','Freeradius Internal'),
(545, NULL,'Tmp-IP-Address-5','1825','ipaddr','Freeradius Internal'),
(546, NULL,'Tmp-IP-Address-6','1826','ipaddr','Freeradius Internal'),
(547, NULL,'Tmp-IP-Address-7','1827','ipaddr','Freeradius Internal'),
(548, NULL,'Tmp-IP-Address-8','1828','ipaddr','Freeradius Internal'),
(549, NULL,'Tmp-IP-Address-9','1829','ipaddr','Freeradius Internal'),
(550, NULL,'Tmp-Octets-0','1830','octets','Freeradius Internal'),
(551, NULL,'Tmp-Octets-1','1831','octets','Freeradius Internal'),
(552, NULL,'Tmp-Octets-2','1832','octets','Freeradius Internal'),
(553, NULL,'Tmp-Octets-3','1833','octets','Freeradius Internal'),
(554, NULL,'Tmp-Octets-4','1834','octets','Freeradius Internal'),
(555, NULL,'Tmp-Octets-5','1835','octets','Freeradius Internal'),
(556, NULL,'Tmp-Octets-6','1836','octets','Freeradius Internal'),
(557, NULL,'Tmp-Octets-7','1837','octets','Freeradius Internal'),
(558, NULL,'Tmp-Octets-8','1838','octets','Freeradius Internal'),
(559, NULL,'Tmp-Octets-9','1839','octets','Freeradius Internal'),
(560, NULL,'Tmp-Date-0','1840','date','Freeradius Internal'),
(561, NULL,'Tmp-Date-1','1841','date','Freeradius Internal'),
(562, NULL,'Tmp-Date-2','1842','date','Freeradius Internal'),
(563, NULL,'Tmp-Date-3','1843','date','Freeradius Internal'),
(564, NULL,'Tmp-Date-4','1844','date','Freeradius Internal'),
(565, NULL,'Tmp-Date-5','1845','date','Freeradius Internal'),
(566, NULL,'Tmp-Date-6','1846','date','Freeradius Internal'),
(567, NULL,'Tmp-Date-7','1847','date','Freeradius Internal'),
(568, NULL,'Tmp-Date-8','1848','date','Freeradius Internal'),
(569, NULL,'Tmp-Date-9','1849','date','Freeradius Internal'),
(570, NULL,'Tmp-Integer64-0','1871','integer64','Freeradius Internal'),
(571, NULL,'Tmp-Integer64-1','1872','integer64','Freeradius Internal'),
(572, NULL,'Tmp-Integer64-2','1873','integer64','Freeradius Internal'),
(573, NULL,'Tmp-Integer64-3','1874','integer64','Freeradius Internal'),
(574, NULL,'Tmp-Integer64-4','1875','integer64','Freeradius Internal'),
(575, NULL,'Tmp-Integer64-5','1876','integer64','Freeradius Internal'),
(576, NULL,'Tmp-Integer64-6','1877','integer64','Freeradius Internal'),
(577, NULL,'Tmp-Integer64-7','1878','integer64','Freeradius Internal'),
(578, NULL,'Tmp-Integer64-8','1879','integer64','Freeradius Internal'),
(579, NULL,'Tmp-Integer64-9','1880','integer64','Freeradius Internal'),
(580, NULL,'Tmp-Cast-String','1851','string','Freeradius Internal'),
(581, NULL,'Tmp-Cast-Integer','1852','integer','Freeradius Internal'),
(582, NULL,'Tmp-Cast-Ipaddr','1853','ipaddr','Freeradius Internal'),
(583, NULL,'Tmp-Cast-Date','1854','date','Freeradius Internal'),
(584, NULL,'Tmp-Cast-Abinary','1855','abinary','Freeradius Internal'),
(585, NULL,'Tmp-Cast-Octets','1856','octets','Freeradius Internal'),
(586, NULL,'Tmp-Cast-Ifid','1857','ifid','Freeradius Internal'),
(587, NULL,'Tmp-Cast-IPv6Addr','1858','ipv6addr','Freeradius Internal'),
(588, NULL,'Tmp-Cast-IPv6Prefix','1859','ipv6prefix','Freeradius Internal'),
(589, NULL,'Tmp-Cast-Byte','1860','byte','Freeradius Internal'),
(590, NULL,'Tmp-Cast-Short','1861','short','Freeradius Internal'),
(591, NULL,'Tmp-Cast-Ethernet','1862','ether','Freeradius Internal'),
(592, NULL,'Tmp-Cast-Signed','1863','signed','Freeradius Internal'),
(593, NULL,'Tmp-Cast-Integer64','1869','integer64','Freeradius Internal'),
(594, NULL,'Tmp-Cast-IPv4Prefix','1870','ipv4prefix','Freeradius Internal'),
(595, NULL,'WiMAX-MN-NAI','1900','string','Freeradius Internal'),
(596, NULL,'TLS-Cert-Serial','1910','string','Freeradius Internal'),
(597, NULL,'TLS-Cert-Expiration','1911','string','Freeradius Internal'),
(598, NULL,'TLS-Cert-Issuer','1912','string','Freeradius Internal'),
(599, NULL,'TLS-Cert-Subject','1913','string','Freeradius Internal'),
(600, NULL,'TLS-Cert-Common-Name','1914','string','Freeradius Internal'),
(601, NULL,'TLS-Cert-Subject-Alt-Name-Email','1915','string','Freeradius Internal'),
(602, NULL,'TLS-Cert-Subject-Alt-Name-Dns','1916','string','Freeradius Internal'),
(603, NULL,'TLS-Cert-Subject-Alt-Name-Upn','1917','string','Freeradius Internal'),
(604, NULL,'TLS-Cert-Valid-Since','1918','string','Freeradius Internal'),
(605, NULL,'TLS-Client-Cert-Serial','1920','string','Freeradius Internal'),
(606, NULL,'TLS-Client-Cert-Expiration','1921','string','Freeradius Internal'),
(607, NULL,'TLS-Client-Cert-Issuer','1922','string','Freeradius Internal'),
(608, NULL,'TLS-Client-Cert-Subject','1923','string','Freeradius Internal'),
(609, NULL,'TLS-Client-Cert-Common-Name','1924','string','Freeradius Internal'),
(610, NULL,'TLS-Client-Cert-Filename','1925','string','Freeradius Internal'),
(611, NULL,'TLS-Client-Cert-Subject-Alt-Name-Email','1926','string','Freeradius Internal'),
(612, NULL,'TLS-Client-Cert-X509v3-Extended-Key-Usage','1927','string','Freeradius Internal'),
(613, NULL,'TLS-Client-Cert-X509v3-Subject-Key-Identifier','1928','string','Freeradius Internal'),
(614, NULL,'TLS-Client-Cert-X509v3-Authority-Key-Identifier','1929','string','Freeradius Internal'),
(615, NULL,'TLS-Client-Cert-X509v3-Basic-Constraints','1930','string','Freeradius Internal'),
(616, NULL,'TLS-Client-Cert-Subject-Alt-Name-Dns','1931','string','Freeradius Internal'),
(617, NULL,'TLS-Client-Cert-Subject-Alt-Name-Upn','1932','string','Freeradius Internal'),
(618, NULL,'TLS-PSK-Identity','1933','string','Freeradius Internal'),
(619, NULL,'TLS-Client-Cert-X509v3-Extended-Key-Usage-OID','1936','string','Freeradius Internal'),
(620, NULL,'TLS-Client-Cert-Valid-Since','1937','string','Freeradius Internal'),
(621, NULL,'TLS-OCSP-Cert-Valid','1943','integer','Freeradius Internal'),
(622, NULL,'TLS-Cache-Filename','1946','string','Freeradius Internal'),
(623, NULL,'TLS-Session-Version','1947','string','Freeradius Internal'),
(624, NULL,'TLS-Session-Cipher-Suite','1948','string','Freeradius Internal'),
(625, NULL,'SoH-MS-Machine-OS-vendor','2100','integer','Freeradius Internal'),
(626, NULL,'SoH-MS-Machine-OS-version','2101','integer','Freeradius Internal'),
(627, NULL,'SoH-MS-Machine-OS-release','2102','integer','Freeradius Internal'),
(628, NULL,'SoH-MS-Machine-OS-build','2103','integer','Freeradius Internal'),
(629, NULL,'SoH-MS-Machine-SP-version','2104','integer','Freeradius Internal'),
(630, NULL,'SoH-MS-Machine-SP-release','2105','integer','Freeradius Internal'),
(631, NULL,'SoH-MS-Machine-Processor','2106','integer','Freeradius Internal'),
(632, NULL,'SoH-MS-Machine-Name','2107','string','Freeradius Internal'),
(633, NULL,'SoH-MS-Correlation-Id','2108','octets','Freeradius Internal'),
(634, NULL,'SoH-MS-Machine-Role','2109','integer','Freeradius Internal'),
(635, NULL,'SoH-Supported','2119','integer','Freeradius Internal'),
(636, NULL,'SoH-MS-Windows-Health-Status','2120','string','Freeradius Internal'),
(637, NULL,'SoH-MS-Health-Other','2129','string','Freeradius Internal'),
(638, NULL,'Radclient-Test-Name','2200','string','Freeradius Internal'),



('EAP-IKEv2-IDType','IPV4_ADDR','1','Freeradius Internal'),
('EAP-IKEv2-IDType','FQDN','2','Freeradius Internal'),
('EAP-IKEv2-IDType','RFC822_ADDR','3','Freeradius Internal'),
('EAP-IKEv2-IDType','IPV6_ADDR','5','Freeradius Internal'),
('EAP-IKEv2-IDType','DER_ASN1_DN','9','Freeradius Internal'),
('EAP-IKEv2-IDType','DER_ASN1_GN','10','Freeradius Internal'),
('EAP-IKEv2-IDType','KEY_ID','11','Freeradius Internal'),
('EAP-IKEv2-AuthType','none','0','Freeradius Internal'),
('EAP-IKEv2-AuthType','secret','1','Freeradius Internal'),
('EAP-IKEv2-AuthType','cert','2','Freeradius Internal'),
('EAP-IKEv2-AuthType','both','3','Freeradius Internal'),
('Send-CoA-Request','No','0','Freeradius Internal'),
('Send-CoA-Request','Yes','1','Freeradius Internal'),
('Module-Return-Code','reject','0','Freeradius Internal'),
('Module-Return-Code','fail','1','Freeradius Internal'),
('Module-Return-Code','ok','2','Freeradius Internal'),
('Module-Return-Code','handled','3','Freeradius Internal'),
('Module-Return-Code','invalid','4','Freeradius Internal'),
('Module-Return-Code','userlock','5','Freeradius Internal'),
('Module-Return-Code','notfound','6','Freeradius Internal'),
('Module-Return-Code','noop','7','Freeradius Internal'),
('Module-Return-Code','updated','8','Freeradius Internal'),
('FreeRADIUS-Client-Require-MA','no','0','Freeradius Internal'),
('FreeRADIUS-Client-Require-MA','yes','1','Freeradius Internal'),
('Allow-Session-Resumption','no','0','Freeradius Internal'),
('Allow-Session-Resumption','yes','1','Freeradius Internal'),
('EAP-Session-Resumed','no','0','Freeradius Internal'),
('EAP-Session-Resumed','yes','1','Freeradius Internal'),
('Chbind-Response-Code','success','2','Freeradius Internal'),
('Chbind-Response-Code','failure','3','Freeradius Internal'),
('Cache-Status-Only','no','0','Freeradius Internal'),
('Cache-Status-Only','yes','1','Freeradius Internal'),
('Cache-Merge','no','0','Freeradius Internal'),
('Cache-Merge','yes','1','Freeradius Internal'),
('Cache-Read-Only','no','0','Freeradius Internal'),
('Cache-Read-Only','yes','1','Freeradius Internal'),
('EAP-Sim-Subtype','Start','10','Freeradius Internal'),
('EAP-Sim-Subtype','Challenge','11','Freeradius Internal'),
('EAP-Sim-Subtype','Notification','12','Freeradius Internal'),
('EAP-Sim-Subtype','Re-authentication','13','Freeradius Internal'),
('TLS-OCSP-Cert-Valid','unknown','3','Freeradius Internal'),
('TLS-OCSP-Cert-Valid','skipped','2','Freeradius Internal'),
('TLS-OCSP-Cert-Valid','yes','1','Freeradius Internal'),
('TLS-OCSP-Cert-Valid','no','0','Freeradius Internal'),
('SoH-MS-Machine-OS-vendor','Microsoft','311','Freeradius Internal'),
('SoH-MS-Machine-Processor','x86','0','Freeradius Internal'),
('SoH-MS-Machine-Processor','i64','6','Freeradius Internal'),
('SoH-MS-Machine-Processor','x86_64','9','Freeradius Internal'),
('SoH-MS-Machine-Role','client','1','Freeradius Internal'),
('SoH-MS-Machine-Role','dc','2','Freeradius Internal'),
('SoH-MS-Machine-Role','server','3','Freeradius Internal'),
('SoH-Supported','no','0','Freeradius Internal'),
('SoH-Supported','yes','1','Freeradius Internal'),
('Auth-Type','Local','1','Freeradius Internal'),
('Auth-Type','Reject','4','Freeradius Internal'),
('Auth-Type','Accept','254','Freeradius Internal'),
('Autz-Type','Local','1','Freeradius Internal'),
('Acct-Type','Local','1','Freeradius Internal'),
('Session-Type','Local','1','Freeradius Internal'),
('Post-Auth-Type','Local','1','Freeradius Internal'),
('Post-Auth-Type','Reject','2','Freeradius Internal'),
('Post-Auth-Type','Challenge','3','Freeradius Internal'),
('Post-Proxy-Type','Fail','1','Freeradius Internal'),
('Post-Proxy-Type','Fail-Authentication','2','Freeradius Internal'),
('Post-Proxy-Type','Fail-Accounting','3','Freeradius Internal'),
('Post-Proxy-Type','Fail-CoA','4','Freeradius Internal'),
('Post-Proxy-Type','Fail-Disconnect','5','Freeradius Internal'),
('Fall-Through','No','0','Freeradius Internal'),
('Fall-Through','Yes','1','Freeradius Internal'),
('Relax-Filter','No','0','Freeradius Internal'),
('Relax-Filter','Yes','1','Freeradius Internal'),
('Strip-User-Name','No','0','Freeradius Internal'),
('Strip-User-Name','Yes','1','Freeradius Internal'),
('Packet-Type','Access-Request','1','Freeradius Internal'),
('Packet-Type','Access-Accept','2','Freeradius Internal'),
('Packet-Type','Access-Reject','3','Freeradius Internal'),
('Packet-Type','Accounting-Request','4','Freeradius Internal'),
('Packet-Type','Accounting-Response','5','Freeradius Internal'),
('Packet-Type','Accounting-Status','6','Freeradius Internal'),
('Packet-Type','Password-Request','7','Freeradius Internal'),
('Packet-Type','Password-Accept','8','Freeradius Internal'),
('Packet-Type','Password-Reject','9','Freeradius Internal'),
('Packet-Type','Accounting-Message','10','Freeradius Internal'),
('Packet-Type','Access-Challenge','11','Freeradius Internal'),
('Packet-Type','Status-Server','12','Freeradius Internal'),
('Packet-Type','Status-Client','13','Freeradius Internal'),
('Packet-Type','Resource-Free-Request','21','Freeradius Internal'),
('Packet-Type','Resource-Free-Response','22','Freeradius Internal'),
('Packet-Type','Resource-Query-Request','23','Freeradius Internal'),
('Packet-Type','Resource-Query-Response','24','Freeradius Internal'),
('Packet-Type','Alternate-Resource-Reclaim-Request','25','Freeradius Internal'),
('Packet-Type','NAS-Reboot-Request','26','Freeradius Internal'),
('Packet-Type','NAS-Reboot-Response','27','Freeradius Internal'),
('Packet-Type','Next-Passcode','29','Freeradius Internal'),
('Packet-Type','New-Pin','30','Freeradius Internal'),
('Packet-Type','Terminate-Session','31','Freeradius Internal'),
('Packet-Type','Password-Expired','32','Freeradius Internal'),
('Packet-Type','Event-Request','33','Freeradius Internal'),
('Packet-Type','Event-Response','34','Freeradius Internal'),
('Packet-Type','Disconnect-Request','40','Freeradius Internal'),
('Packet-Type','Disconnect-ACK','41','Freeradius Internal'),
('Packet-Type','Disconnect-NAK','42','Freeradius Internal'),
('Packet-Type','CoA-Request','43','Freeradius Internal'),
('Packet-Type','CoA-ACK','44','Freeradius Internal'),
('Packet-Type','CoA-NAK','45','Freeradius Internal'),
('Packet-Type','IP-Address-Allocate','50','Freeradius Internal'),
('Packet-Type','IP-Address-Release','51','Freeradius Internal'),
('Response-Packet-Type','Access-Request','1','Freeradius Internal'),
('Response-Packet-Type','Access-Accept','2','Freeradius Internal'),
('Response-Packet-Type','Access-Reject','3','Freeradius Internal'),
('Response-Packet-Type','Accounting-Request','4','Freeradius Internal'),
('Response-Packet-Type','Accounting-Response','5','Freeradius Internal'),
('Response-Packet-Type','Accounting-Status','6','Freeradius Internal'),
('Response-Packet-Type','Password-Request','7','Freeradius Internal'),
('Response-Packet-Type','Password-Accept','8','Freeradius Internal'),
('Response-Packet-Type','Password-Reject','9','Freeradius Internal'),
('Response-Packet-Type','Accounting-Message','10','Freeradius Internal'),
('Response-Packet-Type','Access-Challenge','11','Freeradius Internal'),
('Response-Packet-Type','Status-Server','12','Freeradius Internal'),
('Response-Packet-Type','Status-Client','13','Freeradius Internal'),
('Response-Packet-Type','Disconnect-Request','40','Freeradius Internal'),
('Response-Packet-Type','Disconnect-ACK','41','Freeradius Internal'),
('Response-Packet-Type','Disconnect-NAK','42','Freeradius Internal'),
('Response-Packet-Type','CoA-Request','43','Freeradius Internal'),
('Response-Packet-Type','CoA-ACK','44','Freeradius Internal'),
('Response-Packet-Type','CoA-NAK','45','Freeradius Internal'),
('Response-Packet-Type','Do-Not-Respond','256','Freeradius Internal'),
('EAP-Type','None','0','Freeradius Internal'),
('EAP-Type','Identity','1','Freeradius Internal'),
('EAP-Type','Notification','2','Freeradius Internal'),
('EAP-Type','NAK','3','Freeradius Internal'),
('EAP-Type','MD5-Challenge','4','Freeradius Internal'),
('EAP-Type','EAP-MD5','4','Freeradius Internal'),
('EAP-Type','MD5','4','Freeradius Internal'),
('EAP-Type','One-Time-Password','5','Freeradius Internal'),
('EAP-Type','OTP','5','Freeradius Internal'),
('EAP-Type','Generic-Token-Card','6','Freeradius Internal'),
('EAP-Type','EAP-GTC','6','Freeradius Internal'),
('EAP-Type','GTC','6','Freeradius Internal'),
('EAP-Type','RSA-Public-Key','9','Freeradius Internal'),
('EAP-Type','DSS-Unilateral','10','Freeradius Internal'),
('EAP-Type','KEA','11','Freeradius Internal'),
('EAP-Type','KEA-Validate','12','Freeradius Internal'),
('EAP-Type','EAP-TLS','13','Freeradius Internal'),
('EAP-Type','TLS','13','Freeradius Internal'),
('EAP-Type','Defender-Token','14','Freeradius Internal'),
('EAP-Type','RSA-SecurID-EAP','15','Freeradius Internal'),
('EAP-Type','Arcot-Systems-EAP','16','Freeradius Internal'),
('EAP-Type','Cisco-LEAP','17','Freeradius Internal'),
('EAP-Type','LEAP','17','Freeradius Internal'),
('EAP-Type','Nokia-IP-Smart-Card','18','Freeradius Internal'),
('EAP-Type','EAP-SIM','18','Freeradius Internal'),
('EAP-Type','SIM','18','Freeradius Internal'),
('EAP-Type','SRP-SHA1','19','Freeradius Internal'),
('EAP-Type','EAP-TTLS','21','Freeradius Internal'),
('EAP-Type','TTLS','21','Freeradius Internal'),
('EAP-Type','Remote-Access-Service','22','Freeradius Internal'),
('EAP-Type','EAP-AKA','23','Freeradius Internal'),
('EAP-Type','AKA','23','Freeradius Internal'),
('EAP-Type','3Com-Wireless','24','Freeradius Internal'),
('EAP-Type','PEAP','25','Freeradius Internal'),
('EAP-Type','Microsoft-MS-CHAPv2','26','Freeradius Internal'),
('EAP-Type','MAKE','27','Freeradius Internal'),
('EAP-Type','CRYPTOCard','28','Freeradius Internal'),
('EAP-Type','Cisco-MS-CHAPv2','29','Freeradius Internal'),
('EAP-Type','DynamID','30','Freeradius Internal'),
('EAP-Type','Rob-EAP','31','Freeradius Internal'),
('EAP-Type','SecurID-EAP','32','Freeradius Internal'),
('EAP-Type','MS-Authentication-TLV','33','Freeradius Internal'),
('EAP-Type','SentriNET','34','Freeradius Internal'),
('EAP-Type','Actiontec-Wireless','35','Freeradius Internal'),
('EAP-Type','Cogent-Biomentric-EAP','36','Freeradius Internal'),
('EAP-Type','AirFortress-EAP','37','Freeradius Internal'),
('EAP-Type','HTTP-Digest','38','Freeradius Internal'),
('EAP-Type','TNC','38','Freeradius Internal'),
('EAP-Type','SecuriSuite-EAP','39','Freeradius Internal'),
('EAP-Type','DeviceConnect-EAP','40','Freeradius Internal'),
('EAP-Type','SPEKE','41','Freeradius Internal'),
('EAP-Type','MOBAC','42','Freeradius Internal'),
('EAP-Type','EAP-FAST','43','Freeradius Internal'),
('EAP-Type','FAST','43','Freeradius Internal'),
('EAP-Type','Zonelabs','44','Freeradius Internal'),
('EAP-Type','Link','45','Freeradius Internal'),
('EAP-Type','PAX','46','Freeradius Internal'),
('EAP-Type','PSK','47','Freeradius Internal'),
('EAP-Type','SAKE','48','Freeradius Internal'),
('EAP-Type','EAP-IKEv2','49','Freeradius Internal'),
('EAP-Type','IKEv2','49','Freeradius Internal'),
('EAP-Type','AKA2','50','Freeradius Internal'),
('EAP-Type','GPSK','51','Freeradius Internal'),
('EAP-Type','PWD','52','Freeradius Internal'),
('EAP-Type','EKEv1','53','Freeradius Internal'),
('EAP-Type','EAP-MSCHAPv2','26','Freeradius Internal'),
('EAP-Type','MSCHAPv2','26','Freeradius Internal'),
('EAP-TLS-Require-Client-Cert','No','0','Freeradius Internal'),
('EAP-TLS-Require-Client-Cert','Yes','1','Freeradius Internal'),
('EAP-Code','Request','1','Freeradius Internal'),
('EAP-Code','Response','2','Freeradius Internal'),
('EAP-Code','Success','3','Freeradius Internal'),
('EAP-Code','Failure','4','Freeradius Internal'),
('MS-CHAP-Use-NTLM-Auth','No','0','Freeradius Internal'),
('MS-CHAP-Use-NTLM-Auth','Yes','1','Freeradius Internal');